easy_admin:
  entities:
    Portfolio:
      class: App\Entity\Portfolio
      label: 'Portfolio'
      list:
        title: 'List of all Portfolio'
        help: 'list of Portfolio'
        actions:
          - { name: 'edit', label: '', icon: 'edit' }
          - { name: 'delete', label: '', icon: 'trash' }
        fields:
          - {property: 'id'}
          - {property: 'title'}
          - {property: 'involvement'}
          - {property: 'category'}
          - {property: 'image', template: 'easy_admin/vich_uploader_image.html.twig'}
      edit:
        fields:
          - {property: 'title'}
          - {property: 'involvement'}
          - {property: 'category'}
          - {property: 'url'}
          - {property: 'imageFile',label: 'Logo', type: 'vich_image'}
      new:
        fields:
          - {property: 'title'}
          - {property: 'involvement'}
          - {property: 'category'}
          - {property: 'url'}
          - {property: 'imageFile',label: 'Logo', type: 'vich_image'}